In [1]:
import numpy as np

# 3x4 matrix of zeros
zeros_matrix = np.zeros((3, 4))

# 2x5 matrix of ones
ones_matrix = np.ones((2, 5))

print("Zeros Matrix:")
print(zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\nOnes Matrix:")
print(ones_matrix)
print("Shape:", ones_matrix.shape)

Zeros Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

Ones Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)
